spring:
  datasource:
    pssdb:
      jdbc-url: jdbc:oracle:thin:@jindev.cybtexbvxkgj.ap-northeast-2.rds.amazonaws.com:1521:orcl
      username: stg017
      password: stg017
      driver-class-name: oracle.jdbc.driver.OracleDriver
    emsdb:
      jdbc-url: jdbc:oracle:thin:@emsdb.cybtexbvxkgj.ap-northeast-2.rds.amazonaws.com:1521:EMSDB
      username: jinair
      password: airjin
      driver-class-name: oracle.jdbc.driver.OracleDriver
    intdb:
      jdbc-url: jdbc:oracle:thin:@bidb.cybtexbvxkgj.ap-northeast-2.rds.amazonaws.com:1521:BIDB
      username: airkorea_dev
      password: dev_airkorea16
      driver-class-name: oracle.jdbc.driver.OracleDriver

server:
  scheme: https
  name: stg-crewpnr.jinair.com

# SSO 클라이언트에서 정의해줘야 하는 sso 관련 properties
sso:
  oauth:
    endpoint:
      authorize: https://ssostg.jinair.com/oauth/authorize
      token: https://ssostg.jinair.com/oauth/token
      userinfo: https://ssostg.jinair.com/oauth/userinfo
    client-id: local-crewpnr
    client-secret: a76858d3-7500-475d-9e57-cef18fdf2e36
    scope: ReadProfile,ReadAll,WriteProfile
    redirect-uri: https://stg-crewpnr.jinair.com/sso/callback
  using-dummy-login: true

# 패키지별 로그 레벨
logging:
  level:
    com:
      zaxxer:
        hikari:
          pool:
            HikariPool: INFO
            PoolBase: INFO
    org:
      springframework:
        boot:
          autoconfigure:
            logging:
              ConditionEvaluationReportLogger: INFO
