spring:
  datasource:
    pssdb:
      jdbc-url: jdbc:oracle:thin:@jindev.cybtexbvxkgj.ap-northeast-2.rds.amazonaws.com:1521:orcl
      username: stg017
      password: stg017
      driver-class-name: oracle.jdbc.driver.OracleDriver
    emsdb:
      jdbc-url: jdbc:oracle:thin:@emsdb.cybtexbvxkgj.ap-northeast-2.rds.amazonaws.com:1521:EMSDB
      username: jinair
      password: airjin
      driver-class-name: oracle.jdbc.driver.OracleDriver
    intdb:
      jdbc-url: jdbc:oracle:thin:@bidb.cybtexbvxkgj.ap-northeast-2.rds.amazonaws.com:1521:BIDB
      username: airkorea_dev
      password: dev_airkorea16
      driver-class-name: oracle.jdbc.driver.OracleDriver
  redis:
    host: 10.23.5.231
    port: 6379
  session:
    redis:
      flush-mode: on_save
      namespace: 'spring:session:crewpnr'
    store-type: redis
    timeout: 30

server:
  scheme: https
  name: local-crewpnr.jinair.com
  sevlet:
    session:
      timeout: 1m

# SSO 클라이언트에서 정의해줘야 하는 sso 관련 properties
sso:
  oauth:
    endpoint:
      authorize: https://ssostg.jinair.com/oauth/authorize # 인가 코드 발급
      token: https://ssostg.jinair.com/oauth/token # 토큰 발급
      userinfo: https://ssostg.jinair.com/oauth/userinfo # 사용자 정보 조회
      signout: https://ssostg.jinair.com/logout # 로그아웃
    client-id: local-crewpnr
    client-secret: a76858d3-7500-475d-9e57-cef18fdf2e36
    scope: ReadProfile,ReadAll,WriteProfile
  redirect-path: /sso/callback # sso 로그인 후 전달받을 콜백 url
  logout-path: /sso/signout # sso 로그아웃 url
  ignoring-urls: >
    /swagger-ui/**,
    /v3/api-docs/**,
    /mail/**
  using-dummy-login: true

# 패키지별 로그 레벨
logging:
  level:
    com:
      zaxxer:
        hikari:
          pool:
            HikariPool: INFO
            PoolBase: INFO
    io:
      swagger:
        v3:
          core:
            converter:
              ModelConverterContextImpl: INFO
    org:
      springframework:
        boot:
          autoconfigure:
            logging:
              ConditionEvaluationReportLogger: INFO
