# SSO 클라이언트에서 정의해줘야 하는 sso 관련 properties
sso:
  policies:
    default-return-uri: /
    redirection:
      target-urls: >
        /,
        /reservations,
        /failhistories,
        /swagger-ui/index.html
