### 공통 코드 조회 샘플
GET http://localhost:8080/sample/commoncode/codes/AGT001/01

### 지역 코드 조회 샘플
GET http://localhost:8080/sample/commoncode/regions/NEA

### 국가 코드 조회 샘플
GET http://localhost:8080/sample/commoncode/countries/TWN

### 공항 코드 조회 샘플
GET http://localhost:8080/sample/commoncode/airports/ICN

### 공항 위치에 따른 국내/국제 여부 판단 샘플
GET http://localhost:8080/sample/utils/isDomestic/ICN